name: meu_music
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  http: ^1.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  get: ^4.6.6
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
