// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBURPXA1RG8ut5zir8ixgGVimjeoAruOFk',
    appId: '1:340836263095:web:f5eb8ca231b40881501932',
    messagingSenderId: '340836263095',
    projectId: 'meumusic-98c39',
    authDomain: 'meumusic-98c39.firebaseapp.com',
    storageBucket: 'meumusic-98c39.appspot.com',
    measurementId: 'G-BDZH84H4T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApSFEXP7aXZ3kqxSrwVDcsdJ8YaJh2L54',
    appId: '1:340836263095:android:51f4655d630c75f4501932',
    messagingSenderId: '340836263095',
    projectId: 'meumusic-98c39',
    storageBucket: 'meumusic-98c39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fTeM8NSi8KnRKaJVlswMOqVFkwSDSdA',
    appId: '1:340836263095:ios:e67827f86af8202c501932',
    messagingSenderId: '340836263095',
    projectId: 'meumusic-98c39',
    storageBucket: 'meumusic-98c39.appspot.com',
    iosBundleId: 'com.example.meuMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fTeM8NSi8KnRKaJVlswMOqVFkwSDSdA',
    appId: '1:340836263095:ios:573255effc4e5955501932',
    messagingSenderId: '340836263095',
    projectId: 'meumusic-98c39',
    storageBucket: 'meumusic-98c39.appspot.com',
    iosBundleId: 'com.example.meuMusic.RunnerTests',
  );
}
